"""2nd Migration

Revision ID: 02637d440eb4
Revises: 7f2600aebbc9
Create Date: 2020-10-27 08:50:08.585887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02637d440eb4'
down_revision = '7f2600aebbc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pass_secure', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pass_secure')
    # ### end Alembic commands ###
